# Copyright Broadcom, Inc. All Rights Reserved.
# SPDX-License-Identifier: APACHE-2.0

services:
  mongodb:
    # image: docker.io/bitnami/mongodb:8.0-local
    image: bitnami-mongodb:8.0.4-local
    build:
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
