name: Build Mongo 8 Image

on:
  push:
    branches:
      - main
    paths:
      - 8.0/*
  pull_request:
    paths:
      - 8.0/*

env:
  TAGS: dlavrenuek/bitnami-mongodb-arm:8.0,dlavrenuek/bitnami-mongodb-arm:8.0.4

jobs:
  build-push:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'pull_request' }}
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.TAGS }}
